### ISSUE TITLE
Linting shows liquid-fire lint errors

### ISSUE THREAD

**Issue by topaxi** [martndemus/ember-cli-qunit-eslint#1]
When using in my project with liquid-fire installed, liquid-fire modules seem to get linted too, triggering a lot of errors with my eslint config. I think they should be excluded. I'm not sure if this is a liquid-fire issue as it does not seem to be the case for any other installed module.

**Comment by topaxi** [comment]
This is definitely liquid fire related: https://github.com/ef4/liquid-fire/issues/370

**Comment by martndemus** [comment]
:+1: Thanks for checking and closing!
