### ISSUE TITLE
Support ESLint 2

### ISSUE THREAD

**Issue by chriskrycho** [martndemus/ember-cli-qunit-eslint#4]
There are a number of things that have changed with ESLint 2, including a number of rule definitions. For one such example, I'm running into a missing definition of the `keyword-spacing` rule, which seems to have replaced a couple other similar definitions in ESLint 1.

**Comment by chriskrycho** [comment]
Sorry, just realized this is [an upstream issue](https://github.com/jonathanKingston/broccoli-lint-eslint/pull/9).

**Comment by chriskrycho** [comment]
But, on further reflection, I also realized that once that upstream dependency *is* fixed, this package will still need to be updated. (I'm happy to submit a PR for it once it is.)

**Comment by martndemus** [comment]
👍

**Comment by chriskrycho** [comment]
The upstream is now fixed; it should be possible to bump the version dependency in this shortly (once @jonathanKingston releases those updates to npm).

**Comment by chriskrycho** [comment]
Version dependencies are loose enough here that a clean install (or `rm -rf node_modules; npm install`) resolves the issue nicely now that the upstream is fixed.

**Comment by joukevandermaas** [comment]
Not for me; if I don't fix `broccoli-lint-eslint` to 1.1.1, I can't build my project.

**Comment by chriskrycho** [comment]
Interesting; I’m not specifying broccoli-lint-eslint in my package at all, only getting it through the bits which depend on it.

I do also have ember-cli-eslint installed; does that make a difference?

**Comment by chriskrycho** [comment]
@joukevandermaas are you seeing that issue on Windows, perchance? I'm finding that I can install successfully on OS X but *not* on Windows.

**Comment by joukevandermaas** [comment]
Yes! We're definitely on Windows. Installing `ember-cli-eslint` makes no difference.
________________________________

**Comment by chriskrycho** [comment]
Yeah, our internal testing has identified the issue: it's [upstream], with a platform-dependent-path. I'm testing and putting together a pull-request against it now.

[upstream]: https://github.com/jonathanKingston/broccoli-lint-eslint/issues/15

**Comment by chriskrycho** [comment]
[Relevant PR](https://github.com/jonathanKingston/broccoli-lint-eslint/pull/16)

**Comment by joukevandermaas** [comment]
Thanks! I'll watch npm for a new release of `broccoli-lint-eslint`, since they don't seem to be using github releases.

I really appreciate your help here!
