### ISSUE TITLE
Block node dependencies

### ISSUE THREAD

**Issue by rogatty** [martndemus/ember-cli-qunit-eslint#5]
Hi!
Recently, broccoli-lint-eslint started to require node version that supports ES6, see https://github.com/jonathanKingston/broccoli-lint-eslint/pull/11.

Because of that our build process started to fail (we still have to use node 0.12.x) and we had to create a fork with locked version of broccoli-lint-eslint, see https://github.com/Wikia/ember-cli-qunit-eslint/commit/67a641d04cb23cb09bc311fc1e4f0fb4358c1336.

It would be nice if you could block versions in your repo so we can use it again. Thanks!

**Comment by martndemus** [comment]
@rogatty could you submit a PR for the change?

**Comment by chriskrycho** [comment]
Update: if we bump the dependency to `broccoli-lint-eslint` to `^2.0.0` that should do the trick, I think. He got the ES6 dependencies issue sorted (via pre-compilation via babel before shipping the npm package). I'll submit a PR to that effect @martndemus.
